const colorList = [
    { name: 'Black', hex: '#000000' },
    { name: 'White', hex: '#FFFFFF' },
    { name: 'Red', hex: '#FF0000' },
    { name: 'Green', hex: '#00FF00' },
    { name: 'Blue', hex: '#0000FF' },
    { name: 'Yellow', hex: '#FFFF00' },
    { name: 'Cyan', hex: '#00FFFF' },
    { name: 'Magenta', hex: '#FF00FF' },
    { name: 'Silver', hex: '#C0C0C0' },
    { name: 'Gray', hex: '#808080' },
    { name: 'Maroon', hex: '#800000' },
    { name: 'Olive', hex: '#808000' },
    { name: 'Lime', hex: '#00FF00' },
    { name: 'Aqua', hex: '#00FFFF' },
    { name: 'Teal', hex: '#008080' },
    { name: 'Navy', hex: '#000080' },
    { name: 'Fuchsia', hex: '#FF00FF' },
    { name: 'Purple', hex: '#800080' },
    { name: 'Orange', hex: '#FFA500' },
    { name: 'Pink', hex: '#FFC0CB' },
    { name: 'Brown', hex: '#A52A2A' },
    { name: 'Gold', hex: '#FFD700' },
    { name: 'Turquoise', hex: '#40E0D0' },
    { name: 'Violet', hex: '#EE82EE' },
    { name: 'Sky Blue', hex: '#87CEEB' },
    { name: 'Indigo', hex: '#4B0082' },
    { name: 'Crimson', hex: '#DC143C' },
    { name: 'Hot Pink', hex: '#FF69B4' },
    { name: 'Deep Sky Blue', hex: '#00BFFF' },
    { name: 'Spring Green', hex: '#00FF7F' },
];

export default colorList; 